import 'dart:typed_data';
import 'package:excel/excel.dart';
import 'package:intl/intl.dart';
import '../models/attendance_report_model.dart';

class ExcelExportService {
  Uint8List generateExcel(AttendanceReport report) {
    final excel = Excel.createExcel();
    excel.rename('Sheet1', 'Executive Summary');

    _buildExecutiveSummary(excel, report);
    _buildEmployeesOverview(excel, report);
    _buildDetailedAttendance(excel, report);

    return Uint8List.fromList(excel.encode() ?? []);
  }

  void _buildExecutiveSummary(Excel excel, AttendanceReport report) {
    final sheet = excel['Executive Summary'];

    // Add Report Title
    sheet.appendRow([TextCellValue('PORT ATTENDANCE — EXECUTIVE SUMMARY')]);

    final dateFormat = DateFormat('yyyy-MM-dd');
    final timeFormat = DateFormat('yyyy-MM-dd HH:mm');

    sheet.appendRow([TextCellValue('')]);
    sheet.appendRow([
      TextCellValue('Reporting Period'),
      TextCellValue(
        '${dateFormat.format(report.startDate)} – ${dateFormat.format(report.endDate)}',
      ),
    ]);
    sheet.appendRow([TextCellValue('Scope'), TextCellValue(report.scope)]);
    sheet.appendRow([
      TextCellValue('Generated Date/Time'),
      TextCellValue(timeFormat.format(report.generatedAt)),
    ]);
    sheet.appendRow(
      [TextCellValue('Generated By'), TextCellValue(report.generatedBy)],
    );
    sheet.appendRow([TextCellValue('')]);

    sheet.appendRow([
      TextCellValue('Total Employees'),
      IntCellValue(report.totalEmployees),
    ]);
    sheet.appendRow([
      TextCellValue('Expected Working Days'),
      IntCellValue(report.expectedWorkingDays),
    ]);
    sheet.appendRow([
      TextCellValue('Attendance Records (Present+Late)'),
      IntCellValue(report.present + report.late),
    ]);
    sheet.appendRow([TextCellValue('Present'), IntCellValue(report.present)]);
    sheet.appendRow([TextCellValue('Late'), IntCellValue(report.late)]);
    sheet.appendRow([TextCellValue('Absent'), IntCellValue(report.absent)]);
    sheet.appendRow([TextCellValue('Day Off'), IntCellValue(report.daysOff)]);
    sheet.appendRow([TextCellValue('Leave'), IntCellValue(report.leaves)]);
    sheet.appendRow([TextCellValue('Holidays'), IntCellValue(report.holidays)]);
    sheet.appendRow([
      TextCellValue('Incomplete Records'),
      IntCellValue(report.incompleteRecords),
    ]);
    sheet.appendRow([
      TextCellValue('Overall Attendance Rate'),
      TextCellValue('${report.attendanceRate.toStringAsFixed(1)}%'),
    ]);
    sheet.appendRow([
      TextCellValue('Total Late Hours'),
      DoubleCellValue(report.totalLateMinutes / 60.0),
    ]);
    sheet.appendRow([
      TextCellValue('Total Worked Hours'),
      DoubleCellValue(report.totalWorkedHours),
    ]);

    // Formatting adjustments can be added here
  }

  void _buildEmployeesOverview(Excel excel, AttendanceReport report) {
    final sheet = excel['Employees Overview'];

    sheet.appendRow([
      TextCellValue('Department'),
      TextCellValue('Employee ID'),
      TextCellValue('Employee Name'),
      TextCellValue('Schedule'),
      TextCellValue('Expected Working Days'),
      TextCellValue('Present'),
      TextCellValue('Late'),
      TextCellValue('Absent'),
      TextCellValue('Day Off'),
      TextCellValue('Leave'),
      TextCellValue('Holidays'),
      TextCellValue('Incomplete'),
      TextCellValue('Total Late Hours'),
      TextCellValue('Total Worked Hours'),
      TextCellValue('Attendance Rate (%)'),
    ]);

    for (var emp in report.employeeSummaries) {
      sheet.appendRow([
        TextCellValue(emp.department),
        TextCellValue(emp.employeeId),
        TextCellValue(emp.employeeName),
        TextCellValue(emp.schedule),
        IntCellValue(emp.expectedWorkingDays),
        IntCellValue(emp.present),
        IntCellValue(emp.late),
        IntCellValue(emp.absent),
        IntCellValue(emp.daysOff),
        IntCellValue(emp.leaves),
        IntCellValue(emp.holidays),
        IntCellValue(emp.incomplete),
        DoubleCellValue(emp.totalLateMinutes / 60.0),
        DoubleCellValue(emp.totalWorkedHours),
        DoubleCellValue(emp.attendanceRate),
      ]);
    }
  }

  void _buildDetailedAttendance(Excel excel, AttendanceReport report) {
    final sheet = excel['Detailed Attendance'];

    sheet.appendRow([
      TextCellValue('Date'),
      TextCellValue('Employee ID'),
      TextCellValue('Employee'),
      TextCellValue('Department'),
      TextCellValue('Schedule'),
      TextCellValue('Expected to Work'),
      TextCellValue('Check-in'),
      TextCellValue('Check-out'),
      TextCellValue('Status'),
      TextCellValue('Late (hrs)'),
      TextCellValue('Work Hours'),
      TextCellValue('Device'),
      TextCellValue('Notes'),
    ]);

    final dateFormat = DateFormat('yyyy-MM-dd');
    final timeFormat = DateFormat('HH:mm:ss');

    for (var record in report.detailedRecords) {
      sheet.appendRow([
        TextCellValue(dateFormat.format(record.date)),
        TextCellValue(record.employeeId),
        TextCellValue(record.employeeName),
        TextCellValue(record.department),
        TextCellValue(record.schedule),
        TextCellValue(record.expectedToWork ? 'Yes' : 'No'),
        TextCellValue(
          record.checkIn != null ? timeFormat.format(record.checkIn!) : '—',
        ),
        TextCellValue(
          record.checkOut != null ? timeFormat.format(record.checkOut!) : '—',
        ),
        TextCellValue(record.status),
        DoubleCellValue(record.lateMinutes / 60.0),
        DoubleCellValue(record.workHours),
        TextCellValue(record.device),
        TextCellValue(record.notes),
      ]);
    }
  }
}
