import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/attendance_report_model.dart';

class PdfExportService {
  Future<Uint8List> generatePdf(AttendanceReport report) async {
    final pdf = pw.Document();

    final fontRegular = await PdfGoogleFonts.robotoRegular();
    final fontBold = await PdfGoogleFonts.robotoBold();

    final theme = pw.ThemeData.withFont(
      base: fontRegular,
      bold: fontBold,
    );

    final dateFormat = DateFormat('yyyy-MM-dd');
    final timeFormat = DateFormat('yyyy-MM-dd HH:mm');
    final hmFormat = DateFormat('HH:mm:ss');

    pdf.addPage(
      pw.MultiPage(
        theme: theme,
        pageFormat: PdfPageFormat.a4.landscape, // Landscape for detailed table
        margin: const pw.EdgeInsets.all(32),
        header: (pw.Context context) =>
            _buildHeader(report, dateFormat, timeFormat),
        footer: (pw.Context context) => _buildFooter(context),
        build: (pw.Context context) => [
          _buildExecutiveSummary(report),
          pw.SizedBox(height: 20),
          ..._buildEmployeeSummary(report),
          pw.SizedBox(height: 20),
          ..._buildDetailedAttendance(report, dateFormat, hmFormat),
        ],
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildHeader(
    AttendanceReport report,
    DateFormat dateFormat,
    DateFormat timeFormat,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'PORT ATTENDANCE REPORT',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.blue900,
              ),
            ),
            pw.Text(
              'Generated: ${timeFormat.format(report.generatedAt)}',
              style: const pw.TextStyle(
                fontSize: 10,
                color: PdfColors.grey700,
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 4),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Reporting Period: ${dateFormat.format(report.startDate)} – ${dateFormat.format(report.endDate)}',
              style: const pw.TextStyle(
                fontSize: 12,
                color: PdfColors.grey800,
              ),
            ),
            pw.Text(
              'Generated By: ${report.generatedBy} | Scope: ${report.scope}',
              style: const pw.TextStyle(
                fontSize: 10,
                color: PdfColors.grey700,
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 8),
        pw.Divider(thickness: 1.5, color: PdfColors.blueGrey400),
        pw.SizedBox(height: 12),
      ],
    );
  }

  pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 10),
      child: pw.Text(
        'Page ${context.pageNumber} of ${context.pagesCount}',
        style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
      ),
    );
  }

  pw.Widget _buildExecutiveSummary(AttendanceReport report) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: const pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Executive Summary',
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.blue800,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              _buildSummaryItem(
                'Total Employees',
                report.totalEmployees.toString(),
              ),
              _buildSummaryItem(
                'Attendance Rate',
                '${report.attendanceRate.toStringAsFixed(1)}%',
              ),
              _buildSummaryItem('Present', report.present.toString()),
              _buildSummaryItem('Late', report.late.toString()),
              _buildSummaryItem('Absent', report.absent.toString()),
            ],
          ),
          pw.SizedBox(height: 8),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              _buildSummaryItem('Leave', report.leaves.toString()),
              _buildSummaryItem(
                'Total Worked Hours',
                report.totalWorkedHours.toStringAsFixed(1),
              ),
              _buildSummaryItem(
                'Total Late Hours',
                (report.totalLateMinutes / 60).toStringAsFixed(1),
              ),
              pw.SizedBox(width: 50), // Spacer
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _buildSummaryItem(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          label,
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
        ),
        pw.Text(
          value,
          style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
        ),
      ],
    );
  }

  List<pw.Widget> _buildEmployeeSummary(AttendanceReport report) {
    return [
      pw.Text(
        'Employee Summary',
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headers: [
            'Employee ID',
            'Name',
            'Dept',
            'Sch.',
            'Exp. Days',
            'Present',
            'Late',
            'Absent',
            'Hrs',
            'Rate',
          ],
          headerStyle: pw.TextStyle(
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.white,
            fontSize: 10,
          ),
          headerDecoration: const pw.BoxDecoration(color: PdfColors.blue600),
          cellStyle: const pw.TextStyle(fontSize: 9),
          cellHeight: 20,
          data: report.employeeSummaries
              .map(
                (emp) => [
                  emp.employeeId,
                  emp.employeeName,
                  emp.department,
                  emp.schedule,
                  emp.expectedWorkingDays.toString(),
                  emp.present.toString(),
                  emp.late.toString(),
                  emp.absent.toString(),
                  emp.totalWorkedHours.toStringAsFixed(1),
                  '${emp.attendanceRate.toStringAsFixed(1)}%',
                ],
              )
              .toList(),
        ),
    ];
  }

  List<pw.Widget> _buildDetailedAttendance(
    AttendanceReport report,
    DateFormat dateFormat,
    DateFormat timeFormat,
  ) {
    return [
      pw.Text(
        'Detailed Attendance',
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headers: [
            'Date',
            'Employee',
            'Expected',
            'In',
            'Out',
            'Status',
            'Late (Hrs)',
            'Hrs',
          ],
          headerStyle: pw.TextStyle(
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.white,
            fontSize: 10,
          ),
          headerDecoration:
              const pw.BoxDecoration(color: PdfColors.blueGrey600),
          cellStyle: const pw.TextStyle(fontSize: 9),
          cellHeight: 20,
          data: report.detailedRecords
              .map(
                (r) => [
                  dateFormat.format(r.date),
                  r.employeeName,
                  r.expectedToWork ? 'Yes' : 'No',
                  r.checkIn != null ? timeFormat.format(r.checkIn!) : '—',
                  r.checkOut != null ? timeFormat.format(r.checkOut!) : '—',
                  r.status.toUpperCase(),
                  (r.lateMinutes / 60).toStringAsFixed(1),
                  r.workHours.toStringAsFixed(1),
                ],
              )
              .toList(),
        ),
    ];
  }
}
